let name = "Raj";
let age = 26;
let fav_color = "Green";

console.log(`Name:${name}, Age:${age}, Favourite_Color:${fav_color}`);
console.log("==========================================")
let num=5;

if(num % 2 === 0){
  console.log("The number is even");
}
else if(num % 3===0){
 console.log("Odd number");
}

const num1=23;
const num2 = 33;

console.log(`${num1} + ${num2} = ${num1 + num2}`);
console.log(`${num1} - ${num2} = ${num1 - num2}`);
console.log(`${num1} * ${num2} = ${num1 * num2}`);
console.log(`${num1} / ${num2} = ${num1 / num2}`);